package com.foxdsp.libfun.model;

import com.foxdsp.libfun.model.base.BaseLibclassd;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Libclassd extends BaseLibclassd<Libclassd> {
	public static final Libclassd dao = new Libclassd();
}
