package com.foxdsp.libfun.model;

import com.foxdsp.libfun.model.base.BaseLibclassm;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Libclassm extends BaseLibclassm<Libclassm> {
	public static final Libclassm dao = new Libclassm();
}
