package com.foxdsp.libfun.model;

import com.foxdsp.libfun.model.base.BaseLibconfig;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Libconfig extends BaseLibconfig<Libconfig> {
	public static final Libconfig dao = new Libconfig();
}
