package com.foxdsp.libfun.model;

import com.foxdsp.libfun.model.base.BaseMenus;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Menus extends BaseMenus<Menus> {
	public static final Menus dao = new Menus();
}
