package com.foxdsp.libfun.model;


import com.foxdsp.libfun.model.base.BaseNotifySend;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class NotifySend extends BaseNotifySend<NotifySend> {
	public static final NotifySend dao = new NotifySend();
}
