package com.foxdsp.libfun.model;


import com.foxdsp.libfun.model.base.BaseNotifyMessage;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class NotifyMessage extends BaseNotifyMessage<NotifyMessage> {
	public static final NotifyMessage dao = new NotifyMessage();
}
