package com.foxdsp.libfun.model;

import com.foxdsp.libfun.model.base.BasePrivilege;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Privilege extends BasePrivilege<Privilege> {
	public static final Privilege dao = new Privilege();
}
