package com.foxdsp.libfun.model;

import com.foxdsp.libfun.model.base.BaseRoleprivilege;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Roleprivilege extends BaseRoleprivilege<Roleprivilege> {
	public static final Roleprivilege dao = new Roleprivilege();
}
