package com.foxdsp.libfun.model;


import com.foxdsp.libfun.model.base.BaseSyslog;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Syslog extends BaseSyslog<Syslog> {
	public static final Syslog dao = new Syslog();
}
