package com.foxdsp.libfun.model;

import com.foxdsp.libfun.model.base.BaseUsersext;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Usersext extends BaseUsersext<Usersext> {
	public static final Usersext dao = new Usersext();
}
