package com.foxdsp.libfun.model;

import com.foxdsp.libfun.model.base.BaseUsers;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Users extends BaseUsers<Users> {
	public static final Users dao = new Users();

	public boolean isSuperman() {
		return getSuperMan() != null && getSuperMan().equals(1) ;
	}

	public boolean isInuse() {
		return getInUse() !=null && getInUse().equals(1);
	}
}
