package com.foxdsp.libfun.model;

import com.foxdsp.libfun.model.base.BaseUsersrole;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Usersrole extends BaseUsersrole<Usersrole> {
	public static final Usersrole dao = new Usersrole();
}
