package com.foxdsp.libfun.model.base;

import com.jfinal.plugin.activerecord.IBean;
import com.jfinal.plugin.activerecord.Model;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseMaterialcolumntype<M extends BaseMaterialcolumntype<M>> extends Model<M> implements IBean {

	public void setSeqid(Integer Seqid) {
		set("Seqid", Seqid);
	}

	public Integer getSeqid() {
		return get("Seqid");
	}

	public void setTypename(String typename) {
		set("typename", typename);
	}

	public String getTypename() {
		return get("typename");
	}

	public void setBelongTo(Integer belongTo) {
		set("belongTo", belongTo);
	}

	public Integer getBelongTo() {
		return get("belongTo");
	}

	public void setKeyvalue(String keyvalue) {
		set("keyvalue", keyvalue);
	}

	public String getKeyvalue() {
		return get("keyvalue");
	}

	public void setWidth(String width) {
		set("width", width);
	}

	public String getWidth() {
		return get("width");
	}

	public void setHeight(String height) {
		set("height", height);
	}

	public String getHeight() {
		return get("height");
	}

	public void setIsBlank(String isBlank) {
		set("isBlank", isBlank);
	}

	public String getIsBlank() {
		return get("isBlank");
	}

	public void setLength(Integer length) {
		set("length", length);
	}

	public Integer getLength() {
		return get("length");
	}

	public void setSize(Integer size) {
		set("size", size);
	}

	public Integer getSize() {
		return get("size");
	}

	public void setExpression(String expression) {
		set("expression", expression);
	}

	public String getExpression() {
		return get("expression");
	}

	public void setSelectValue(String selectValue) {
		set("selectValue", selectValue);
	}

	public String getSelectValue() {
		return get("selectValue");
	}

	public void setRemark(String remark) {
		set("remark", remark);
	}

	public String getRemark() {
		return get("remark");
	}

}
