package com.foxdsp.libfun.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseLibconfig<M extends BaseLibconfig<M>> extends Model<M> implements IBean {

	public void setSeqId(Long SeqId) {
		set("SeqId", SeqId);
	}

	public Long getSeqId() {
		return get("SeqId");
	}

	public void setConfigNo(String ConfigNo) {
		set("ConfigNo", ConfigNo);
	}

	public String getConfigNo() {
		return get("ConfigNo");
	}

	public void setConfigName(String ConfigName) {
		set("ConfigName", ConfigName);
	}

	public String getConfigName() {
		return get("ConfigName");
	}

	public void setConfigValue(String ConfigValue) {
		set("ConfigValue", ConfigValue);
	}

	public String getConfigValue() {
		return get("ConfigValue");
	}

	public void setRemark(String Remark) {
		set("Remark", Remark);
	}

	public String getRemark() {
		return get("Remark");
	}

	public void setEditBy(String EditBy) {
		set("EditBy", EditBy);
	}

	public String getEditBy() {
		return get("EditBy");
	}

	public void setEditTime(String EditTime) {
		set("EditTime", EditTime);
	}

	public String getEditTime() {
		return get("EditTime");
	}

}
