package com.foxdsp.libfun.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseLibclassm<M extends BaseLibclassm<M>> extends Model<M> implements IBean {

	public void setSeqId(Long SeqId) {
		set("SeqId", SeqId);
	}

	public Long getSeqId() {
		return get("SeqId");
	}

	public void setClassNo(String ClassNo) {
		set("ClassNo", ClassNo);
	}

	public String getClassNo() {
		return get("ClassNo");
	}

	public void setClassName(String ClassName) {
		set("ClassName", ClassName);
	}

	public String getClassName() {
		return get("ClassName");
	}

	public void setRemark(String Remark) {
		set("Remark", Remark);
	}

	public String getRemark() {
		return get("Remark");
	}

}
