package com.foxdsp.libfun.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseRoleprivilege<M extends BaseRoleprivilege<M>> extends Model<M> implements IBean {

	public void setSeqid(java.math.BigInteger seqid) {
		set("seqid", seqid);
	}

	public java.math.BigInteger getSeqid() {
		return get("seqid");
	}

	public void setRoleno(String roleno) {
		set("roleno", roleno);
	}

	public String getRoleno() {
		return get("roleno");
	}

	public void setPrivilegeid(java.math.BigInteger privilegeid) {
		set("privilegeid", privilegeid);
	}

	public java.math.BigInteger getPrivilegeid() {
		return get("privilegeid");
	}

}
