package com.foxdsp.libfun.model.base;

import com.jfinal.plugin.activerecord.IBean;
import com.jfinal.plugin.activerecord.Model;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseMaterialtype<M extends BaseMaterialtype<M>> extends Model<M> implements IBean {

	public void setSeqid(Integer Seqid) {
		set("Seqid", Seqid);
	}

	public Integer getSeqid() {
		return get("Seqid");
	}

	public void setMaterialno(String materialno) {
		set("materialno", materialno);
	}

	public String getMaterialno() {
		return get("materialno");
	}

	public void setMaterialname(String materialname) {
		set("materialname", materialname);
	}

	public String getMaterialname() {
		return get("materialname");
	}

	public void setMaterialtypename(String materialtypename) {
		set("materialtypename", materialtypename);
	}

	public String getMaterialtypename() {
		return get("materialtypename");
	}

	public void setPageurl(String pageurl) {
		set("pageurl", pageurl);
	}

	public String getPageurl() {
		return get("pageurl");
	}

	public void setRemark(String remark) {
		set("remark", remark);
	}

	public String getRemark() {
		return get("remark");
	}

}
