package com.foxdsp.libfun.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseMenus<M extends BaseMenus<M>> extends Model<M> implements IBean {

	public void setSeqId(java.math.BigInteger SeqId) {
		set("SeqId", SeqId);
	}

	public java.math.BigInteger getSeqId() {
		return get("SeqId");
	}

	public void setMenuNo(String MenuNo) {
		set("MenuNo", MenuNo);
	}

	public String getMenuNo() {
		return get("MenuNo");
	}

	public void setMenuName(String MenuName) {
		set("MenuName", MenuName);
	}

	public String getMenuName() {
		return get("MenuName");
	}

	public void setPMenuNo(String PMenuNo) {
		set("PMenuNo", PMenuNo);
	}

	public String getPMenuNo() {
		return get("PMenuNo");
	}

	public void setMenuUrl(String MenuUrl) {
		set("MenuUrl", MenuUrl);
	}

	public String getMenuUrl() {
		return get("MenuUrl");
	}

	public void setDisplayOrder(Integer DisplayOrder) {
		set("DisplayOrder", DisplayOrder);
	}

	public Integer getDisplayOrder() {
		return get("DisplayOrder");
	}

	public void setInUse(Integer InUse) {
		set("InUse", InUse);
	}

	public Integer getInUse() {
		return get("InUse");
	}

}
