package com.foxdsp.libfun.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseUsersrole<M extends BaseUsersrole<M>> extends Model<M> implements IBean {

	public void setSeqid(java.math.BigInteger seqid) {
		set("seqid", seqid);
	}

	public java.math.BigInteger getSeqid() {
		return get("seqid");
	}

	public void setUsername(String username) {
		set("username", username);
	}

	public String getUsername() {
		return get("username");
	}

	public void setRoleno(String roleno) {
		set("roleno", roleno);
	}

	public String getRoleno() {
		return get("roleno");
	}

}
