package com.foxdsp.libfun.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseNotifySend<M extends BaseNotifySend<M>> extends Model<M> implements IBean {

	public void setSeqid(Long seqid) {
		set("seqid", seqid);
	}

	public Long getSeqid() {
		return get("seqid");
	}

	public void setReceiverUserlogno(String receiverUserlogno) {
		set("receiver_userlogno", receiverUserlogno);
	}

	public String getReceiverUserlogno() {
		return get("receiver_userlogno");
	}

	public void setSenderUserlogno(String senderUserlogno) {
		set("sender_userlogno", senderUserlogno);
	}

	public String getSenderUserlogno() {
		return get("sender_userlogno");
	}

	public void setTitle(String title) {
		set("title", title);
	}

	public String getTitle() {
		return get("title");
	}

	public void setSendContent(String sendContent) {
		set("send_content", sendContent);
	}

	public String getSendContent() {
		return get("send_content");
	}

	public void setIsTop(Boolean isTop) {
		set("is_top", isTop);
	}

	public Boolean getIsTop() {
		return get("is_top");
	}

	public void setSendTime(java.util.Date sendTime) {
		set("send_time", sendTime);
	}

	public java.util.Date getSendTime() {
		return get("send_time");
	}

	public void setStatus(Boolean status) {
		set("status", status);
	}

	public Boolean getStatus() {
		return get("status");
	}

	public void setCreatedTime(java.util.Date createdTime) {
		set("created_time", createdTime);
	}

	public java.util.Date getCreatedTime() {
		return get("created_time");
	}

	public void setEditTime(java.util.Date editTime) {
		set("edit_time", editTime);
	}

	public java.util.Date getEditTime() {
		return get("edit_time");
	}

}
