package com.foxdsp.libfun.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseSyslog<M extends BaseSyslog<M>> extends Model<M> implements IBean {

	public void setSeqid(Long seqid) {
		set("seqid", seqid);
	}

	public Long getSeqid() {
		return get("seqid");
	}

	public void setVisitTime(java.util.Date visitTime) {
		set("visit_time", visitTime);
	}

	public java.util.Date getVisitTime() {
		return get("visit_time");
	}

	public void setMethod(String method) {
		set("method", method);
	}

	public String getMethod() {
		return get("method");
	}

	public void setIp(String ip) {
		set("ip", ip);
	}

	public String getIp() {
		return get("ip");
	}

	public void setUrl(String url) {
		set("url", url);
	}

	public String getUrl() {
		return get("url");
	}

	public void setUserlogno(String userlogno) {
		set("userlogno", userlogno);
	}

	public String getUserlogno() {
		return get("userlogno");
	}

	public void setTime(Long time) {
		set("time", time);
	}

	public Long getTime() {
		return get("time");
	}

}
