package com.foxdsp.libfun.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseUsersext<M extends BaseUsersext<M>> extends Model<M> implements IBean {

	public void setSeqid(java.math.BigInteger seqid) {
		set("seqid", seqid);
	}

	public java.math.BigInteger getSeqid() {
		return get("seqid");
	}

	public void setUsersId(java.math.BigInteger usersId) {
		set("usersId", usersId);
	}

	public java.math.BigInteger getUsersId() {
		return get("usersId");
	}

	public void setDaily(Boolean daily) {
		set("daily", daily);
	}

	public Boolean getDaily() {
		return get("daily");
	}

	public void setWeekly(Boolean weekly) {
		set("weekly", weekly);
	}

	public Boolean getWeekly() {
		return get("weekly");
	}

	public void setActivityOver(Boolean activityOver) {
		set("activityOver", activityOver);
	}

	public Boolean getActivityOver() {
		return get("activityOver");
	}

}
